### ISSUE TITLE
generate trainset

### ISSUE THREAD

**Issue by Halfyuan77** [phatli/TransLoc4D#1]
Hello, thank you for your open source code. 
When I am generating the dictionary for training, I find that many frames cannot find their positive frames.（ntu-rsvi/train）
![generate](https://github.com/user-attachments/assets/7e64f6b9-7947-4843-b1dc-790a9d128ebe)

**Comment by phatli** [comment]
Thanks for your interest in our work.
This piece of code fails to filter those queries that have no positive. Will make new changes to improve it.
Luckily the training process should not be impacted by empty positives given they are filtered [here](https://github.com/phatli/TransLoc4D/blob/2b2a3804f8cb63a71660531361a3d8e79da05e81/transloc4d/models/losses/truncated_smoothap.py#L93C9-L93C22) and we set a large batch_size.
Hope this clarifies.

**Comment by Halfyuan77** [comment]
Thank you so much for your quick reply and for maintaining this great work!
